services:
  - type: web
    name: dmaihxcai
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: PIKAFISH_ENGINE
        value: /app/src/pikafish
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: dmaihxcai
      - key: MONGODB_COLLECTION
        value: app_state
